# Generated by Django 4.1.5 on 2023-02-12 15:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_rename_date_of_creation_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(blank=True, max_length=128, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
